In [2]:
from datascience import *
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

In [6]:
flowers=Table.read_table("flowers.csv")
flowers

Petals | Name      | Color
8      | lotus     | pink
34     | sunflower | yellow
5      | rose      | red

In [7]:
country = ["USA", "Netherlands", "Brazil"]

In [8]:
flowers =flowers.with_column("Country", country)
flowers

Petals | Name      | Color  | Country
8      | lotus     | pink   | USA
34     | sunflower | yellow | Netherlands
5      | rose      | red    | Brazil

In [13]:
petalas = flowers.column("Petals")
petalas

array([ 8, 34,  5])

In [47]:
flowers

Petals | Name      | Color  | Country
8      | lotus     | pink   | USA
34     | sunflower | yellow | Netherlands
5      | rose      | red    | Brazil

In [22]:
flowers.num_rows

3

In [23]:
flowers.num_columns

4

In [25]:
flowers.select("Petals","Color")

Petals | Color
8      | pink
34     | yellow
5      | red

In [27]:
flowers.drop("Country","Color")

Petals | Name
8      | lotus
34     | sunflower
5      | rose

In [9]:
year = make_array(1,2,4)
year

array([1, 2, 4])

In [10]:
flowers = flowers.with_column("Year", year)

In [32]:
# encontrar a flor com mais petalas
petalas = flowers.column("Petals")
max(petalas)

34

In [33]:
flowers.column("Petals").max()

34

In [34]:
max(flowers.column("Petals"))

34

In [18]:
petunia_da_mata = [56,"Petunia da Mata","azul","Brazil",3]
petunia_da_mata

[56, 'Petunia da Mata', 'azul', 'Brazil', 3]

In [19]:
flowers = flowers.with_row(petunia_da_mata)
flowers

Petals | Name            | Color  | Country     | Year
8      | lotus           | pink   | USA         | 1
34     | sunflower       | yellow | Netherlands | 2
5      | rose            | red    | Brazil      | 4
56     | Petunia da Mata | azul   | Brazil      | 3
56     | Petunia da Mata | azul   | Brazil      | 3

In [26]:
flowers

Petals | Name            | Color  | Country     | Year
8      | lotus           | pink   | USA         | 1
34     | sunflower       | yellow | Netherlands | 2
5      | rose            | red    | Brazil      | 4
56     | Petunia da Mata | azul   | Brazil      | 3
56     | Petunia da Mata | azul   | Brazil      | 3

In [14]:
flowers.labels

('Petals', 'Name', 'Color', 'Country', 'Year')

In [16]:
# extrai o primeiro valor da coluna Petals na tabela
flowers.column("Petals").item(0)

'8'

In [17]:
# extrai os dados do primeiro registro da tabela
flowers.row(0)

Row(Petals='8', Name='lotus', Color='pink', Country='USA', Year='1')

In [20]:
# extrai o primeiro e terceiro registro da tabela, em forma de tabela
flowers.take(0,2)

Petals | Name  | Color | Country | Year
8      | lotus | pink  | USA     | 1
5      | rose  | red   | Brazil  | 4

In [24]:
numero_registros = np.arange(0,4,1)
numero_registros

array([0, 1, 2, 3])

In [25]:
flowers.take(numero_registros)

Petals | Name            | Color  | Country     | Year
8      | lotus           | pink   | USA         | 1
34     | sunflower       | yellow | Netherlands | 2
5      | rose            | red    | Brazil      | 4
56     | Petunia da Mata | azul   | Brazil      | 3

In [27]:
numero_registros
print(numero_registros)
print(type(numero_registros))

numero_registros = numero_registros.tolist()
print(numero_registros)
print(type(numero_registros))

[0 1 2 3]
<class 'numpy.ndarray'>
[0, 1, 2, 3]
<class 'list'>


In [30]:
lista_numpy = np.arange(0,4).tolist()
lista_numpy

[0, 1, 2, 3]

In [32]:
flowers = flowers.relabeled("Country", "Country (Origin)")
flowers

Petals | Name            | Color  | Country (Origin) | Year
8      | lotus           | pink   | USA              | 1
34     | sunflower       | yellow | Netherlands      | 2
5      | rose            | red    | Brazil           | 4
56     | Petunia da Mata | azul   | Brazil           | 3
56     | Petunia da Mata | azul   | Brazil           | 3