In [1]:
from datascience import *
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

# Arrays

In [2]:
make_array(1,2,3)

array([1, 2, 3])

In [3]:
make_array(1,2,3) * 2

array([2, 4, 6])

In [4]:
make_array(1,2,3) + 5

array([6, 7, 8])

In [5]:
a = make_array(1,2,3)
a

array([1, 2, 3])

In [6]:
a + make_array(10,100,1000)

array([  11,  102, 1003])

In [7]:
max(a)

3

In [8]:
sum(a)

6

In [10]:
list = [1,2,3]
list

[1, 2, 3]

In [11]:
sum(list)

6

In [14]:
fed_budget_2002 = 2370000000000
fed_budget_2012 = 3380000000000
g = (fed_budget_2012/ fed_budget_2002) ** (1/10) -1

fed_budget_2002 * (1+g) **2

2544380256026.486

In [15]:
fed_budget_2002 * (1+g) **3

2636324418804.039

In [16]:
fed_budget_2002 * (1+g) **a

array([2.45564273e+12, 2.54438026e+12, 2.63632442e+12])